version: 1.0.1.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: hmOHCc5y11I6UOdB3pd5tKfjj2BahmonuLmkREbnwoUGOaeHa8AY8OuNhD2kAy75
  skip_symbols: true
